<?php
/**
 * @file
 * drpl_terms.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function drpl_terms_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Murcia',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0060ce37-e9fc-436b-bc14-b564634dcb4d',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Cuenca',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '00fb5daa-c8bd-4c59-b7fb-8d06ab92311d',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Valencia',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '050ed533-46b0-4979-b841-abfd112fdacf',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Toledo',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '118cfe8f-84f4-487f-b068-9a590a22ce32',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Navarra',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '158cd89e-1a97-4574-b795-6ad4de654ade',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Cáceres',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '16adb0a0-4171-446f-bd97-26caa9cae119',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Rioja, La',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1815ebda-8cc9-45af-9a9a-57da50e675d4',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Valladolid',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1cbee9f6-46cd-4272-b0f3-3fbaff30bbba',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Guadalajara',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1ddf5cc5-f513-49c7-ae78-b1cf1e605141',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Tarragona',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2b9910e4-d7de-4516-827f-6355bdb3b159',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Jaén',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2e7a763b-57c9-4756-a1dd-e44d42986324',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Pontevedra',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '310c62aa-dfb1-457b-9478-eececdb27388',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ávila',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3779e6d5-e1d7-4bab-8bc0-039f9728ddfe',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Balears, Illes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '38e98bc2-1407-40e0-85ec-b07560ece328',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Servidor 2',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '39e02977-7fb7-4b48-8b4e-4af04bfe26ce',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'video_servers',
    'field_link' => array(
      'und' => array(
        0 => array(
          'url' => 'http://madridorg-live.hls.adaptive.level3.net/hls-live/madridorg-madridmux/_definst_/live.m3u8',
          'title' => 'Servidor 2',
          'attributes' => array(),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Cantabria',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3a8a4519-d5a4-4191-a2da-eb145d75a4a5',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Cádiz',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3ea67afc-fc16-43f2-8fce-30ab307eaea6',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Sevilla',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4124dba9-c2ae-4d49-936d-461c9118d660',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Burgos',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4d75dd35-4085-4f9c-9882-ba3e645453da',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Zaragoza',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4ebc6fc7-f8e9-4a90-ba37-1a2188ecfd32',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Granada',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '531834f0-6bb1-4fb8-b4b4-83aba58f60b1',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Servidor 1',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '57c9dff1-31d8-4195-ae6b-4f93a9651d87',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'video_servers',
    'field_link' => array(
      'und' => array(
        0 => array(
          'url' => 'http://emisionrdp.madrid.org:80/4CB729B4CB014F069A9506A59341A556021/mobile/playlist.m3u8',
          'title' => 'Servidor 1 ',
          'attributes' => array(),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Gipuzkoa',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '59dea3f6-6283-4798-a53d-592a35d361f0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Salamanca',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '62d28368-eef6-4043-b263-0452911c0566',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Madrid',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6c293e68-07d7-40b2-818f-6693b370675a',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Segovia',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6e88304a-4981-4453-b83c-6703318c89bd',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Girona',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '77b325ec-0fa1-48c2-b5d9-c23e26328dc0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Asturias',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '77ef7a4f-6033-4d43-adb0-d65627922d6d',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Coruña, A',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7ba6d28c-3c28-47b7-9d2a-a8f1af67112e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Soria',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8875c5cf-5f4c-4dd8-a12b-7bc73f7f62c5',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ceuta',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8a88d826-fc59-4f1d-a451-8fc3fcbc6772',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Santa Cruz de Tenerife',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8b5d228a-a104-49f5-998a-5bb9ac2f6756',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'León',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '904e1ae6-ca27-4b74-98f9-404096dec6c4',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Álava',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9445583c-2814-4fe7-80df-d5cffa431e34',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Bizkaia',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9640dcca-fd09-4f0f-81ab-319dd93a77cf',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Albacete',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '978444fe-bef4-4055-97b8-3acc6f1605cf',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Palmas, Las',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9b34793b-7d4c-4f62-ac49-a76d91c32302',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Lugo',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9ccbcd9b-d302-49a0-9ae1-16d0a82a416c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Badajoz',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9fb7b8bc-71f7-4740-a387-8e7ecb3c8325',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Málaga',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ab988979-5453-4df3-89c4-21b706bc41a9',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Huelva',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b6063b35-fdd5-4b6d-b37a-9fd5942308b5',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Castellón',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c5d5e668-5f84-47df-bc2a-7725f5189f4c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Melilla',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c6c07bcf-9cc6-4aea-9b8d-d8be40a143b1',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Almería',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c721c42b-f1c6-4629-b735-450e5c02e69e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Teruel',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cd9272d9-8c78-47fa-b28d-2c2d07b69266',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Palencia',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ce2c9408-92ce-41ce-b659-5444b16a3809',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ourense',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd81b0eab-75b9-4e9b-b709-c2e68f0e4c03',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Córdoba',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'df7ab87e-dd4d-4273-ba51-726726e2796e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Huesca',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e21a5a9a-0c71-48b0-9b7a-d0d94e74e763',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Lleida',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e361625d-45bb-4c10-8ec2-d3d39bd61f91',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Alicante',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e450d095-d6dd-49fe-a558-1ac7c613c706',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Zamora',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'eab244a5-1cf3-4516-a54e-421f87fde15c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ciudad Real',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ec2e8922-0d12-46a0-8fdc-99864ffe3083',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Barcelona',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f40206b3-96b1-4519-8772-bc0ab168d0b5',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'provinces',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
